### PR TITLE
The allow list missing policyset is breaking the generator subscription

### PR DESCRIPTION
**Pull request by gparvin**
The lack of the PolicySet kind in the allow list for the subscription
is now breaking the geneator test.

Signed-off-by: Gus Parvin <gparvin@redhat.com>

### CODE REVIEW

**Review by dhaiducek — COMMENTED** [review]
LGTM! Probably good to have this in general. Should we go ahead and add `policy.open-cluster-management.io/v1alpha1` for completeness?

**Review by dhaiducek — APPROVED** [review]
Looking closer, this only affects the generator. `v1alpha1` probably isn't necessary. Approved!

**Comment by JustinKuli** [comment]
Good catch @dhaiducek, I hadn't noticed that those flags were used in patches here

**Review by JustinKuli — APPROVED** [review]

**Comment by gparvin** [comment]
When issue https://github.com/stolostron/backlog/issues/22546 was opened we were not seeing this problem, but since it's happening now I'm mentioning that issue as the reason for this PR.  Note that it's the same testcase as the original canary failure.

**Comment by dhaiducek** [comment]
/retest (failure appears to be environmental)

```
 • [FAILED] [211.381 seconds]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan [policy-collection, stable, BVT]
/go/src/github.com/stolostron/governance-policy-framework/test/integration/policy_comp_operator_test.go:145
  Test stable/policy-comp-operator
  /go/src/github.com/stolostron/governance-policy-framework/test/integration/policy_comp_operator_test.go:166
    [It] Profile bundle pods should be running
    /go/src/github.com/stolostron/governance-policy-framework/test/integration/policy_comp_operator_test.go:222
  Begin Captured GinkgoWriter Output >>
    STEP: Checking if pod ocp4-pp has been created 05/23/22 19:36:57.7
    STEP: Checking if pod ocp4-pp is running 05/23/22 19:39:12.924
    STEP: Checking if pod rhcos4-pp has been created 05/23/22 19:40:03.963
    STEP: Checking if pod rhcos4-pp is running 05/23/22 19:40:03.991
  << End Captured GinkgoWriter Output
  Expected
      <*fmt.wrapError | 0xc0007c41e0>: {
          msg: "unexpected error when reading response body. Please retry. Original error: read tcp 10.129.220.171:47014->44.205.211.45:6443: read: connection reset by peer",
          err: <*net.OpError | 0xc000946730>{
              Op: "read",
              Net: "tcp",
              Source: <*net.TCPAddr | 0xc00075fcb0>{
                  IP: [10, 129, 220, 171],
                  Port: 47014,
                  Zone: "",
              },
              Addr: <*net.TCPAddr | 0xc00075fce0>{IP: ",\xcd\xd3-", Port: 6443, Zone: ""},
              Err: <*os.SyscallError | 0xc0007c4140>{
                  Syscall: "read",
                  Err: <syscall.Errno>0x68,
              },
          },
      }
  to be nil
  In [It] at: /go/src/github.com/stolostron/governance-policy-framework/test/integration/policy_comp_operator_test.go:244 
```

**Pull request merged**
