### PR TITLE
[2.10] Add the compliance history tests

### PR DESCRIPTION
**Pull request by mprahl**
The cherry-pick for this was missed.

### CODE REVIEW

**Review by yiraeChristineKim — DISMISSED** [review]

**Comment by mprahl** [comment]
Sorry @yiraeChristineKim , I wasn't working with the latest changes from main when I copied the test over.

**Comment by dhaiducek** [comment]
The same test keeps failing. I didn't check, but does the downstream gatekeeper test updates also need to be pulled in here?

**Comment by yiraeChristineKim** [comment]
Let me create a cluster and fix this

**Comment by dhaiducek** [comment]
I think this entire commit just needs to be pulled in. I think only the compliance history bits got updated in this PR: https://github.com/stolostron/governance-policy-framework/commit/f68bb0b552deee67863f5e0d36bc3b8eec2f0f8c

**Comment by dhaiducek** [comment]
Of course now that I say that, the most recent failure is the same one: https://redhat-internal.slack.com/archives/CUS1VB8P3/p1711658066131449

So maybe it's a flake this PR just keeps hitting...

**Comment by mprahl** [comment]
> Of course now that I say that, the most recent failure is the same one: https://redhat-internal.slack.com/archives/CUS1VB8P3/p1711658066131449
> 
> So maybe it's a flake this PR just keeps hitting...

@dhaiducek I pulled in your commit for the downstream Gatekeeper fixes.

**Comment by mprahl** [comment]
@dhaiducek and @yiraeChristineKim it looks like there was a misnamed ConfigurationPolicy since it's supposed to match in `policy-gk-prereq.yaml` and `policy-gk-prereq2.yaml`. The latest commit here addresses that and the main branch fix is at #771.

**Comment by mprahl** [comment]
@yiraeChristineKim and @dhaiducek I finally got this to pass :laughing:

**Review by dhaiducek — APPROVED** [review]

**Comment by dhaiducek** [comment]
#773

**Review by yiraeChristineKim — APPROVED** [review]

**Pull request merged**
