### PR TITLE
[release-2.4] Simplify the Gatekeeper tests

### PR DESCRIPTION
**Pull request by JustinKuli**
Based on cf34fcd1bf63347c1812c7f435cf21f25afd9019

Testing the Gatekeeper functionality is out of scope for the BVT/SVT/E2E tests since that is limited to the ACM Governance functionality. This should be handled by the Gatekeeper and Gatekeeper operator tests instead.

This was prompted by these tests often taking longer than the max timeout of 10 minutes that is set, and thus leading to flaky BVT and SVT results.

Refs:
 - https://github.com/stolostron/backlog/issues/26656

Signed-off-by: Justin Kulikauskas <jkulikau@redhat.com>

### CODE REVIEW

**Review by ChunxiAlexLuo — APPROVED** [review]
/lgtm

**Comment by mprahl** [comment]
@JustinKuli could you please investigate the CI failure?

**Review by mprahl — DISMISSED** [review]

**Review by mprahl — APPROVED** [review]

**Comment by JustinKuli** [comment]
```
2022-11-07T19:04:30+00:00 ERROR Deploy hub-1: Timeout (900s) waiting for MCH CR
2022-11-07T19:04:34+00:00 Deployments done. Checking status.
2022-11-07T19:04:34+00:00 Cluster hub-1: ERROR Failed with status: ERROR WAIT_MCH
```

**Comment by dhaiducek** [comment]
I'm suspicious...that was too easy 😆

**Pull request merged**
