### PR TITLE
Use an older API version of ManagedClusterSet

### PR DESCRIPTION
**Pull request by mprahl**
This ensures more compatibility across ACM versions.

Relates:
https://github.com/stolostron/backlog/issues/26834

### CODE REVIEW

**Review by JustinKuli — DISMISSED** [review]

**Comment by mprahl** [comment]
@JustinKuli could you please review the last commit?

**Review by JustinKuli — APPROVED** [review]

**Comment by mprahl** [comment]
It seems that this will not work in 2.7. I'll close this and reopen a PR with the unrelated commit that fixes CI.

**Pull request closed without merging**
