### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by dhaiducek**
ref: https://issues.redhat.com/browse/ACM-8326

### CODE REVIEW

**Comment by JustinKuli** [comment]
I wonder if we should hold this until the other upgrade PRs pass CI (just to prevent some drift)

**Comment by dhaiducek** [comment]
/hold

> I wonder if we should hold this until the other upgrade PRs pass CI (just to prevent some drift)

Oh wow, the others bombed so hard I assumed this one did too! Agree!

**Review by yiraeChristineKim — APPROVED** [review]

**Pull request merged**
