### PR TITLE
Remove the Kyverno policy test

### PR DESCRIPTION
**Pull request by mprahl**
The Kyverno Helm chart has gotten too large to be supported by Application Subscription, so the policy that installs Kyverno can no longer be used.

See the following comment:
https://github.com/stolostron/backlog/issues/27329#issuecomment-1602619144

### CODE REVIEW

**Review by dhaiducek — APPROVED** [review]

**Comment by mprahl** [comment]
/override "Framework KinD / Tests (latest, false, hosted)"

**Pull request merged**
