### PR TITLE
OperatorPolicy test fixes

### PR DESCRIPTION
**Pull request by dhaiducek**
- Check the message before compliance (since that test failure could be more helpful)
- Fetch the CSV name dynamically (since a static version could be flaky if a new z-stream is released)
- Only attempt an OperatorGroup/CSV deletion if a name was discovered
- Clean up all CSV when deployed clusterwide (this is mainly for the benefit of the Canaries)

Followup to:
- #743 
- #736

### CODE REVIEW

**Comment by dhaiducek** [comment]
Looks like 2 `Disabled` events were generated:
```
   [FAILED] Timed out after 30.000s.
  The function passed to Eventually failed at /go/src/github.com/stolostron/governance-policy-framework/test/integration/compliance_history_test.go:338 with:
  expected cluster local-cluster to have one disabled events
  Expected
      <[]interface {} | len:2, cap:2>: [ 
```
FYI @mprahl

**Comment by dhaiducek** [comment]
CI is passing here now! 🎉

**Review by gparvin — APPROVED** [review]

**Pull request merged**
