### PR TITLE
Extend login retry interval

### PR DESCRIPTION
**Pull request by dhaiducek**
This matches the interval in `policy_generator_acm_hardening.go`. It also updates a deprecated `ioutils` function.

### CODE REVIEW

**Review by mprahl — APPROVED** [review]

**Comment by dhaiducek** [comment]
The status checks have passed and this PR is ready for review.

I've attached some additional changes to this PR:
- Pass `Gomega` to the compliance state check for it's assertion
- Extend the image vulnerability CSV check

**Review by gparvin — APPROVED** [review]
lgtm

**Pull request merged**
