### PR TITLE
Add Test Case For Zts-Cmc Policy

### PR DESCRIPTION
**Pull request by mahesh-zetta**
Signed-off-by: Mahesh Bhoothapuri <mahesh@zettaset.com>

### CODE REVIEW

**Review by gparvin — APPROVED** [review]
Thanks for working with us to create the policy and the test!

**Comment by gparvin** [comment]
It was a policyreport test that failed the validation -- I think it might be the same one that failed in one of my other PRs so I suspect it's something in our framework -- not this new test.
/retest

**Comment by gparvin** [comment]
Failed to get a cluster... I'll retest later

**Comment by mahesh-zetta** [comment]
> Failed to get a cluster... I'll retest later

The error does not seem to be related to the new test I added.   Please let me know if I need to provide any info.

**Comment by gparvin** [comment]
I think it's other tests
/retest

**Comment by gparvin** [comment]
I think our CI is broken for this test until https://github.com/stolostron/governance-policy-framework/pull/418 merges.  Will need to try this again afterwards.

**Comment by gparvin** [comment]
The test keeps failing in our framework.  It just looks like we aren't able to reserve a cluster for testing.
/retest

**Comment by gparvin** [comment]
@dhaiducek I keep getting failures to get a cluster to test on.  Any idea why this PR would keep getting those failures?  Do I just need to keep trying or is something broken somewhere?

**Comment by dhaiducek** [comment]
This is expected. The `policy-grc-cp-prow` ClusterPool has been exhausted, and the timeout in the Prow workflow isn't long enough for a new cluster to be created. You'll need to check the ClusterPool to be sure there are clusters before restarting the test. (You can also bump the ClusterPool size if you feel you might need to retest again soon.)

**Pull request merged**
