### PR TITLE
Increase verify policy on all clusters func timeout

### PR DESCRIPTION
**Pull request by yiraeChristineKim**
Increase verifyPolicyOnAllClusters timeout from 30 secs to 60 secs as we discussed

Ref: https://redhat-internal.slack.com/archives/CUS1VB8P3/p1712154840798339

### CODE REVIEW

**Review by dhaiducek — DISMISSED** [review]

**Review by mprahl — CHANGES_REQUESTED** [review]
@yiraeChristineKim did you mean to change the call verifyPolicyOnAllClusters instead? The timeout is configurable in its arguments.

**Review by dhaiducek — APPROVED** [review]

**Review by mprahl — APPROVED** [review]

**Pull request merged**
