### PR TITLE
Pin the kind CLI version

### PR DESCRIPTION
**Pull request by mprahl**
This prevents GitHub rate limiting causing failures in the tests. It
additionally provides a consistent version on each test run to improve the
stability of the tests.

This also makes the run-e2e-tests.sh script fail on HTTP errors.

### CODE REVIEW

**Review by dhaiducek — DISMISSED** [review]

**Comment by mprahl** [comment]
@dhaiducek could you please review again? It seems that the OS TravisCI is using has an older version of curl so I had to use a different flag.

**Review by dhaiducek — APPROVED** [review]

**Pull request merged**
