### PR TITLE
Add some notes to the rotation script

### PR DESCRIPTION
**Pull request by JustinKuli**
Some details were slightly unclear to a first-timer (me).

### CODE REVIEW

**Review by yiraeChristineKim — DISMISSED** [review]

**Review by dhaiducek — CHANGES_REQUESTED** [review]
Thanks for the updates! Looks great!
Would you also add a note in the Vault section to contact a member of the team if it's the first time logging in and the secrets aren't viewable?

**Review by dhaiducek — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
