### PR TITLE
Patch Kyverno AppSub PlacementRule in policy instead of directly

### PR DESCRIPTION
**Pull request by dhaiducek**
Addresses:
- https://github.com/stolostron/backlog/issues/25225

### CODE REVIEW

**Review by mprahl — APPROVED** [review]

**Comment by dhaiducek** [comment]
Oops. I assumed the `PlacementRule` was from the policy, but it's actually an object deployed as part of a RHACM Application. I'll need to do a bit more investigation here.

**Comment by mprahl** [comment]
@dhaiducek could you please provide more context for this change?

**Comment by dhaiducek** [comment]
I was looking at this failure:
```
• [FAILED] [382.036 seconds]
GRC: [P1][Sev1][policy-grc] Test the kyverno generator policies [policy-collection, stable]
/go/src/github.com/stolostron/governance-policy-framework/test/integration/policy_kyverno_generators_test.go:19
  [It] Install Kyverno on the managed cluster
  /go/src/github.com/stolostron/governance-policy-framework/test/integration/policy_kyverno_generators_test.go:38
  Begin Captured GinkgoWriter Output >>
    STEP: Creating kyverno resources by deploying the community policy 08/21/22 12:03:08.537
    STEP: Checking that policy-install-kyverno exists on the Hub cluster 08/21/22 12:03:09.891
    STEP: Patching remediationAction = enforce on the root policy 08/21/22 12:03:09.937
    STEP: Patching the kyverno subscription's placement rule in the policy 08/21/22 12:03:09.977
    STEP: Checking that placementrule kyverno-placement-1 exists on the Hub cluster 08/21/22 12:03:16.409
    STEP: Patching the actual placement rule 08/21/22 12:03:27.837
    STEP: Checking if the status of the root policy is Compliant 08/21/22 12:03:34.254
    Kyverno generator test Kubernetes info:
  << End Captured GinkgoWriter Output
  Timed out after 300.000s.
  Expected
      <nil>: nil
  to equal
      <v1.ComplianceState>: Compliant
  In [It] at: /go/src/github.com/stolostron/governance-policy-framework/test/integration/policy_kyverno_generators_test.go:91
```
https://app.travis-ci.com/github/stolostron/canary/jobs/580401754#L5979-L6001

So this change:
- Checks for noncompliance up front to make sure the policy is active and is reporting status.
- In addition, I found it odd that this test enforces the policy and then updates the Application PlacemenRule inside of it directly rather than through the policy, so this instead patches the policy itself and then enforces the policy to propagate the change.

**Review by mprahl — APPROVED** [review]

**Pull request merged**
