### PR TITLE
Remove completed compliance scan checks from BVT

### PR DESCRIPTION
**Pull request by dhaiducek**
Our E8 and CIS scan policies do have checks for `AGGREGATING` and `DONE`, so it's probably reckless/irresponsible to remove the checks entirely. However, given the length of time it takes for a scan to complete, this PR removes those checks from the BVT so that the scan checks only run on SVT.

~(I'll need to verify that moving these labels works as expected, but I think it should.)~

### CODE REVIEW

**Comment by dhaiducek** [comment]
These labels appeared as expected, skipping over the scan aggregating/done checks:
```
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-comp-operator stable/policy-comp-operator should be created on hub [policy-collection, stable, BVT]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-comp-operator stable/policy-comp-operator should be created on managed cluster [policy-collection, stable, BVT]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-comp-operator stable/policy-comp-operator should be noncompliant [policy-collection, stable, BVT]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-comp-operator Enforcing stable/policy-comp-operator [policy-collection, stable, BVT]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-comp-operator Compliance operator pod should be running [policy-collection, stable, BVT]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-comp-operator Profile bundle pods should be running [policy-collection, stable, BVT]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-comp-operator stable/policy-comp-operator should be compliant [policy-collection, stable, BVT]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-comp-operator Informing stable/policy-comp-operator [policy-collection, stable, BVT]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-e8-scan create and enforce the stable/policy-e8-scan policy stable/policy-e8-scan should be created on hub [policy-collection, stable, BVT]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-e8-scan create and enforce the stable/policy-e8-scan policy stable/policy-e8-scan should be created on managed cluster [policy-collection, stable, BVT]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-e8-scan create and enforce the stable/policy-e8-scan policy Enforcing stable/policy-e8-scan [policy-collection, stable, BVT]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-e8-scan create and enforce the stable/policy-e8-scan policy ComplianceSuite e8 should be created [policy-collection, stable, BVT]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-e8-scan create and enforce the stable/policy-e8-scan policy Informing stable/policy-e8-scan [policy-collection, stable, BVT]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-e8-scan verify the stable/policy-e8-scan has completed its scan ComplianceCheckResult should be created [policy-collection, stable]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-e8-scan verify the stable/policy-e8-scan has completed its scan ComplianceSuite e8 scan results should be AGGREGATING [policy-collection, stable]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-e8-scan verify the stable/policy-e8-scan has completed its scan ComplianceSuite e8 scan results should be DONE [policy-collection, stable]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-cis-scan create and enforce the stable/policy-cis-scan policy stable/policy-cis-scan should be created on hub [policy-collection, stable, BVT]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-cis-scan create and enforce the stable/policy-cis-scan policy stable/policy-cis-scan should be created on managed cluster [policy-collection, stable, BVT]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-cis-scan create and enforce the stable/policy-cis-scan policy Enforcing stable/policy-cis-scan [policy-collection, stable, BVT]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-cis-scan create and enforce the stable/policy-cis-scan policy ComplianceSuite cis should be created [policy-collection, stable, BVT]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-cis-scan create and enforce the stable/policy-cis-scan policy Informing stable/policy-cis-scan [policy-collection, stable, BVT]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-cis-scan verify the stable/policy-cis-scan has completed its scan ComplianceCheckResult should be created [policy-collection, stable]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-cis-scan verify the stable/policy-cis-scan has completed its scan ComplianceSuite cis scan results should be AGGREGATING [policy-collection, stable]
RHACM4K-2222 GRC: [P1][Sev1][policy-grc] Test compliance operator and scan Test stable/policy-cis-scan verify the stable/policy-cis-scan has completed its scan ComplianceSuite cis scan results should be DONE [policy-collection, stable]
```

**Review by mprahl — DISMISSED** [review]

**Review by mprahl — APPROVED** [review]

**Pull request merged**
