### PR TITLE
Update insights client and metrics selector

### PR DESCRIPTION
**Pull request by JustinKuli**
The insights components are now deployed through this chart:
https://github.com/stolostron/multiclusterhub-operator/tree/release-2.6/pkg/templates/charts/toggle/insights/templates

During that change, some of the labels needed to be updated so that
these tests can get the right resources.

Refs:
 - https://github.com/stolostron/backlog/issues/24278

Signed-off-by: Justin Kulikauskas <jkulikau@redhat.com>

### CODE REVIEW

**Review by mprahl — APPROVED** [review]

**Comment by JustinKuli** [comment]
Need to wait for the clusterpool to recover after the other PR

**Comment by JustinKuli** [comment]
Needs https://github.com/openshift/release/pull/30493 so it can test against a 2.6 cluster with the insights changes

**Pull request merged**
