### PR TITLE
[release-2.2] Update org references to `stolostron`

### PR DESCRIPTION
**Pull request by ycao56**
https://github.com/stolostron/backlog/issues/18738
Signed-off-by: Yu Cao <ycao@redhat.com>

### CODE REVIEW

**Comment by ycao56** [comment]
test image built and verified in https://app.travis-ci.com/github/stolostron/governance-policy-framework/builds/244619146

**Review by dhaiducek — DISMISSED** [review]

**Comment by ycao56** [comment]
@dhaiducek This PR is ready for merge.

**Comment by dhaiducek** [comment]
The `policy-collection` links need to be updated also.

**Comment by dhaiducek** [comment]
https://github.com/stolostron/governance-policy-framework/blob/8d37e0a8a35b2df4cc545c0fde1c21c5da28c941/test/policy-collection/policy_gatekeeper_operator_test.go#L43-L45

**Comment by dhaiducek** [comment]
...and they still reference the `master` branch. 😬

**Comment by ycao56** [comment]
@dhaiducek done. I used a specific commit as policy-collection is not branched. We need to think about branching it in the future when there is significant change.

**Review by dhaiducek — APPROVED** [review]

**Pull request merged**
